### ISSUE TITLE
YAML parser incompatible encoded characters in inventories labelled items

### ISSUE THREAD

**Issue by leagris** [Multiverse/Multiverse-Inventories#101]
This player yml inventory fail to load because of "Jambi�res"

Plaintext localized item labels as introduced in CB1.4+, are stored with a YAML parser incompatible encoding.

``` log
Cannot load plugins/Multiverse-Inventories/worlds/ressource/skiller83.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable character '�' (0xFFFD) special characters are not allowed
in "<string>", position 419
```

``` YAML
SURVIVAL:
  armorContents: '{"3":{"d":75,"e":{"PROTECTION_ENVIRONMENTAL":4,"OXYGEN":3},"t":310,"n":{"RepairCost;3":2,"display;10":{"Name;8":"Casque
    en diams a skiller83"}}},"2":{"d":75,"e":{"PROTECTION_ENVIRONMENTAL":4},"t":311,"n":{"RepairCost;3":2,"display;10":{"Name;8":"Plastron
    en diams a skiller83"}}},"1":{"d":75,"e":{"PROTECTION_PROJECTILE":4},"t":312,"n":{"RepairCost;3":2,"display;10":{"Name;8":"Jambi�res
    en diams a skiller83"}}},"0":{"d":76,"e":{"PROTECTION_FALL":4,"PROTECTION_FIRE":3},"t":313,"n":{"RepairCost;3":2,"display;10":{"Name;8":"Bottes
    en diams a skiller83"}}}}'
  bedSpawnLocation: '{"ya":0.0,"wo":"ressource","pi":0.0,"z":301.0,"y":55.0,"x":60.0}'
  inventoryContents: '{"21":{"t":375},"3":{"#":19,"t":352},"20":{"#":64,"t":50},"2":{"#":12,"t":287},"1":{"#":37,"t":297},"0":{"d":427,"e":{"DAMAGE_ALL":3,"KNOCKBACK":2},"t":276,"n":{}},"6":{"d":220,"t":261},"32":{"t":281},"31":{"#":64,"t":50},"4":{"#":3,"t":289},"8":{"#":2,"t":3},"12":{"t":325}}'
  enderChestContents: '{}'
  potions: '[]'
  stats: '{"ra":"300","ex":"3.2598422","hp":"19","fl":"10","txp":"8615","el":"19","ma":"300","sa":"0.0","xp":"0.40042835","ft":"-20","fd":"0.0"}'
```
