### ISSUE TITLE
Item filters per group

### ISSUE THREAD

**Issue by dumptruckman** [Multiverse/Multiverse-Inventories#2]
config to look like so:

```
groups:
    group1:
        worlds:
        - world1
        - world2
        shares:
        - inventory
        blacklist:
            world1:
            - tnt
    group2:
        worlds:
        - world2
        - world3
        shares:
        - inventory
        - health
```
