### ISSUE TITLE
Users are randomly set into wrong game modes on respawn

### ISSUE THREAD

**Issue by burdoto** [Multiverse/Multiverse-Inventories#327]
A user on my 1.13.2 server has been talking to me about him getting put into creative mode on respawn randomly. I have set up a creative world with `Multiverse-Inventories-3.0.0-SNAPSHOT`; config below. I am not exactly sure what this error origins from, although I only use WorldGuard and Multiverse Inventories to manage game modes. WorldGuard has set creative mode _nowhere_ in the config; so I am assuming this is a Multiverse bug.

Inventories config:
```yaml
# Multiverse-Inventories Groups

# To ADD, DELETE, and EDIT groups use the command /mvinv group.
# No support will be given for those who manually edit these groups.
groups:
  default: # i am REMOVING this share very soon in an attempt to fight this bug
    worlds:
    - world
    - world_the_end
    - world_nether
    shares:
    - all
  creative:
    worlds:
    - amplified
    - creative-plots
    shares:
    - all
  survival:
    worlds:
    - world
    - world_the_end
    - world_nether
    shares:
    - all
```
